cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
        path('', views.cart_detail, name='cart_detail'),
        path('add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
        ]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
        path('', views.product_list, name='product_list'),
        path('<slug:category_slug>/', views.product_list,
             name='product_list_by_category'),
        path('<int:id>/<slug:slug>/', views.product_detail,
             name='product_detail'),
        path('<int:id>/<slug:slug>/popup', views.product_detail_popup,
             name='product_detail_popup'),
        ]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
# add cart to the product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    template_name = 'shop/product/list.html'
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  template_name,
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   # add cart to the product
                   'cart_product_form': cart_product_form})


def product_detail_popup(request, id, slug):
    template_name = 'shop/product/product_detail_popup.html'
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  template_name,
                  {"product": product,
                   "cart_product_form": cart_product_form})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block shop_content %}
    <div class="product-detail">

        <img src="{% if product.image %}{{ product.image.url }} {% else %}
        {% static "img/no_image.png" %}{% endif %}">

        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}</a></h2>

        <p class="price">${{ product.price }}</p>

        <form action="{% url "cart:cart_add" product.id %}" method="POST">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description|linebreaks }}

    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load i18n static %}

{% load static %}

{% block title %}
    {% if category %} {{ category.name }} {% else %} Products {% endif %}
{% endblock %}


{% block shop_content %}

    <div class="sidebar col-sm-12 col-md-4 col-lg-3">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %} class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>

    <!--PRODUCT LIST-->
    <div id="main" class="container">
            <h1>{% if category %} {{ category.name }} {% else %}Products {% endif %}</h1>
            {% for product in products %}
            <!--CARD-->
                <div class="card" style="width: 15rem;">
                    <div class="img-container">
                        <a class="product-list" href="{{ product.get_absolute_url }}"
                           data-popup-url="{% url "shop:product_detail_popup" product.id product.slug %}">
                            <img class="img-card" src="{% if product.image %}
                                            {{ product.image.url }}
                                      {% else %}
                                            {% static "img/no_image.png" %}
                                      {% endif %}">
                        </a>
                    </div>
                    <div class="card-body">
                        <a href="{{ product.get_absolute_url }}"
                           data-popup-url="{% url "shop:product_detail_popup" product.id product.slug %}">{{ product.name }}</a>
                        <br>
                        ${{ product.price }}
                    </div>
                </div>
            {% endfor %}
    </div>
{% endblock %}

{% block extrabody %}
<div id="popup" class="modal fade" tabindex="-1" role="dialog"
     aria-hidden="true" aria-labelledby="popup-modal-title">
    <div class="modal-dialog modal-dialog-centered"
         role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="popup-modal-title"
                    class="modal-title"></h4>
                <button type="button" class="close"
                        data-dismiss="modal"
                        aria-label="{% trans 'Close' %}">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/product_list.js' %}"></script>
{% endblock %}

shop/templates/shop/product/product_detail_popup.html
{% load static %}
{% load i18n %}
<div class="detail_popup">
    <div class="image-div">
        <img class="img-size" src="{% if product.image %}{{ product.image.url }} {% else %}
        {% static "img/no_image.png" %} {% endif %}">
    </div>

    <div class="image-title">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}</a></h2>

        <p class="price">${{ product.price }}</p>

        <form action="{% url "cart:cart_add" product.id %}" method="POST">
            {% csrf_token %}
            {{ cart_product_form }}
            <input type="submit" value="Add to cart">
        </form>
    </div>
</div>