accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views as acounts_views
from .forms import AuthenticationForm


app_name = 'accounts'

urlpatterns = [
        path('login/', auth_views.LoginView.as_view(
                                                template_name='user_accounts/login.html',
                                                authentication_form=AuthenticationForm), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='user_accounts/logout.html'), name='logout'),
        path('signup/', acounts_views.signup, name='signup'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
        path('', views.cart_detail, name='cart_detail'),
        path('add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
        ]

templates/_loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="{% url 'accounts:logout' %}" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <span class="navbar-brand">Logged As: {{ user.username }}</span>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Log Out</a>
        </li>
    </ul>
</form>

{% else %}
<div>
<ul class="navbar-nav">
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}"> Log In</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}"> Sign Up</a></li>
</ul>
</div>
{% endif %}

templates/_navigation.html
<header class="site-header">
        <nav class="navbar navbar-dark navbar-expand-md fixed-top"
                  style="background-color: #5f788a;" >

            <div class="container">
                <!--navbar brand-->
                    <a class="navbar-brand mr-4" href="/">JMR App</a>
                    <button type="button" class="navbar-toggler"
                        data-toggle="collapse" data-target="#navbarNav"
                        aria-expanded="false" aria-controls="navbarToggle">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                <!--navbar home about-->
                <div id="navbarNav" class="collapse navbar-collapse">
                    <div class="navbar-nav mr-auto">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/">
                                    <i class="fa fa-home" aria-hidden="true"></i> HOME
                                </a>
                            </li>
                            <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="/cart/">
                                    <i class="fa fa-shopping-cart"
                                       aria-hidden="true"></i> Cart
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                <!--end navbar home-->

                <!--snippets login signup-->
                {% include '_loginpartial.html' %}
            </div>
        </div>
    </nav>
    </header>

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta chartset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} My Shop {% endblock title %}</title>

        {% load static %}
        {% block stylesheets %}
            <link rel="stylesheet" type="text/css"  href="{% static 'bootstrap4/css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css"  href="{% static 'bootstrap4/css/site.css' %}">
            <link rel="stylesheet" type="text/css"  href="{% static 'style/css/all.min.css' %}">
        {% endblock %}
    </head>

    <body>
        <!--NAVIGATION-->
        {% include '_navigation.html' %}
        <!-------->

        <div class="container">
            <div class="starter-template">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}

                {% endblock %}
                {% block extrabody %}

                {% endblock %}
           </div>
        </div>
        <!--JAVASCRIPT-->
        {% block js %}
            <script src="{% static 'bootstrap4/js/jquery-3.3.1.min.js' %}"> </script>
            <script src="{% static 'bootstrap4/js/popper.min.js' %}"> </script>
            <script src="{% static 'bootstrap4/js/bootstrap.min.js' %}"> </script>
        {% endblock js %}
    </body>
</html>