cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
        path('', views.cart_detail, name='cart_detail'),
        path('add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
        ]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
        path('', views.product_list, name='product_list'),
        path('<slug:category_slug>/', views.product_list,
             name='product_list_by_category'),
        path('<int:id>/<slug:slug>/', views.product_detail,
             name='product_detail'),
        path('<int:id>/<slug:slug>/popup', views.product_detail_popup,
             name='product_detail_popup'),
        ]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
# add cart to the product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    template_name = 'shop/product/list.html'
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  template_name,
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   # add cart to the product
                   'cart_product_form': cart_product_form})


def product_detail_popup(request, id, slug):
    template_name = 'shop/product/product_detail_popup.html'
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  template_name,
                  {"product": product,
                   "cart_product_form": cart_product_form})

shop/templates/shop/base.html
{% extends "base.html" %}

{% block title %}

{% endblock title %}
{% load static %}

<!--CSS-->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css"  href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/shop.css' %}">
{% endblock stylesheets %}
<!--END_css-->

{% block content %}
        <div class="header">

        </div>
        <div class="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                Your Cart:
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} item {{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
            </div>
        </div>
        <div class="content">
            {% block shop_content %}

            {% endblock %}
        </div>
{% endblock %}